/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface EmailLoginRequest : NSObject <TBase, NSCoding> {
  NSString * __email;
  NSString * __password;

  BOOL __email_isset;
  BOOL __password_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
#endif

- (id) init;
- (id) initWithEmail: (NSString *) email password: (NSString *) password;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) password;
- (void) setPassword: (NSString *) password;
#endif
- (BOOL) passwordIsSet;

@end

@interface EmailLoginResponse : NSObject <TBase, NSCoding> {
  int64_t __user_id;
  int32_t __email_state;
  int32_t __gift;
  NSString * __session;

  BOOL __user_id_isset;
  BOOL __email_state_isset;
  BOOL __gift_isset;
  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, getter=email_state, setter=setEmail_state:) int32_t email_state;
@property (nonatomic, getter=gift, setter=setGift:) int32_t gift;
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithUser_id: (int64_t) user_id email_state: (int32_t) email_state gift: (int32_t) gift session: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
#endif
- (BOOL) user_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) email_state;
- (void) setEmail_state: (int32_t) email_state;
#endif
- (BOOL) email_stateIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gift;
- (void) setGift: (int32_t) gift;
#endif
- (BOOL) giftIsSet;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface SocialLoginRequest : NSObject <TBase, NSCoding> {
  NSString * __open_id;

  BOOL __open_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=open_id, setter=setOpen_id:) NSString * open_id;
#endif

- (id) init;
- (id) initWithOpen_id: (NSString *) open_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) open_id;
- (void) setOpen_id: (NSString *) open_id;
#endif
- (BOOL) open_idIsSet;

@end

@interface SocialLoginResponse : NSObject <TBase, NSCoding> {
  int64_t __user_id;
  int32_t __gift;
  NSString * __session;
  BOOL __is_first;

  BOOL __user_id_isset;
  BOOL __gift_isset;
  BOOL __session_isset;
  BOOL __is_first_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, getter=gift, setter=setGift:) int32_t gift;
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=is_first, setter=setIs_first:) BOOL is_first;
#endif

- (id) init;
- (id) initWithUser_id: (int64_t) user_id gift: (int32_t) gift session: (NSString *) session is_first: (BOOL) is_first;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
#endif
- (BOOL) user_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gift;
- (void) setGift: (int32_t) gift;
#endif
- (BOOL) giftIsSet;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_first;
- (void) setIs_first: (BOOL) is_first;
#endif
- (BOOL) is_firstIsSet;

@end

@interface authConstants : NSObject {
}
@end
