/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface RecommendPocket : NSObject <TBase, NSCoding> {
  int64_t __pocket_id;
  NSString * __pocket_cover_photo;
  NSString * __pocket_title;

  BOOL __pocket_id_isset;
  BOOL __pocket_cover_photo_isset;
  BOOL __pocket_title_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
@property (nonatomic, retain, getter=pocket_cover_photo, setter=setPocket_cover_photo:) NSString * pocket_cover_photo;
@property (nonatomic, retain, getter=pocket_title, setter=setPocket_title:) NSString * pocket_title;
#endif

- (id) init;
- (id) initWithPocket_id: (int64_t) pocket_id pocket_cover_photo: (NSString *) pocket_cover_photo pocket_title: (NSString *) pocket_title;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_cover_photo;
- (void) setPocket_cover_photo: (NSString *) pocket_cover_photo;
#endif
- (BOOL) pocket_cover_photoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_title;
- (void) setPocket_title: (NSString *) pocket_title;
#endif
- (BOOL) pocket_titleIsSet;

@end

@interface GetRecommendPocketRequest : NSObject <TBase, NSCoding> {
  NSString * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface GetRecommendPocketResponse : NSObject <TBase, NSCoding> {
  NSMutableArray * __pocket_list;

  BOOL __pocket_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=pocket_list, setter=setPocket_list:) NSMutableArray * pocket_list;
#endif

- (id) init;
- (id) initWithPocket_list: (NSMutableArray *) pocket_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) pocket_list;
- (void) setPocket_list: (NSMutableArray *) pocket_list;
#endif
- (BOOL) pocket_listIsSet;

@end

@interface RecommendUser : NSObject <TBase, NSCoding> {
  int64_t __user_id;
  NSString * __user_name;
  NSString * __user_avatar;
  NSString * __user_domain;

  BOOL __user_id_isset;
  BOOL __user_name_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
#endif

- (id) init;
- (id) initWithUser_id: (int64_t) user_id user_name: (NSString *) user_name user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
#endif
- (BOOL) user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

@end

@interface GetRecommendUserRequest : NSObject <TBase, NSCoding> {
  NSString * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface GetRecommendUserResponse : NSObject <TBase, NSCoding> {
  NSMutableArray * __user_list;

  BOOL __user_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=user_list, setter=setUser_list:) NSMutableArray * user_list;
#endif

- (id) init;
- (id) initWithUser_list: (NSMutableArray *) user_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) user_list;
- (void) setUser_list: (NSMutableArray *) user_list;
#endif
- (BOOL) user_listIsSet;

@end

@interface FeedContent : NSObject <TBase, NSCoding> {
  int32_t __feed_type;
  NSString * __content;
  int64_t __content_id;
  int32_t __content_type;
  int64_t __user_id;
  NSString * __user_name;
  NSString * __user_avatar;
  NSString * __user_domain;
  double __feed_time;

  BOOL __feed_type_isset;
  BOOL __content_isset;
  BOOL __content_id_isset;
  BOOL __content_type_isset;
  BOOL __user_id_isset;
  BOOL __user_name_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
  BOOL __feed_time_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=feed_type, setter=setFeed_type:) int32_t feed_type;
@property (nonatomic, retain, getter=content, setter=setContent:) NSString * content;
@property (nonatomic, getter=content_id, setter=setContent_id:) int64_t content_id;
@property (nonatomic, getter=content_type, setter=setContent_type:) int32_t content_type;
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
@property (nonatomic, getter=feed_time, setter=setFeed_time:) double feed_time;
#endif

- (id) init;
- (id) initWithFeed_type: (int32_t) feed_type content: (NSString *) content content_id: (int64_t) content_id content_type: (int32_t) content_type user_id: (int64_t) user_id user_name: (NSString *) user_name user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain feed_time: (double) feed_time;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) feed_type;
- (void) setFeed_type: (int32_t) feed_type;
#endif
- (BOOL) feed_typeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content;
- (void) setContent: (NSString *) content;
#endif
- (BOOL) contentIsSet;

#if !__has_feature(objc_arc)
- (int64_t) content_id;
- (void) setContent_id: (int64_t) content_id;
#endif
- (BOOL) content_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) content_type;
- (void) setContent_type: (int32_t) content_type;
#endif
- (BOOL) content_typeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
#endif
- (BOOL) user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

#if !__has_feature(objc_arc)
- (double) feed_time;
- (void) setFeed_time: (double) feed_time;
#endif
- (BOOL) feed_timeIsSet;

@end

@interface GetFeedRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  double __time_stamp;
  int32_t __time_flag;

  BOOL __session_isset;
  BOOL __time_stamp_isset;
  BOOL __time_flag_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=time_stamp, setter=setTime_stamp:) double time_stamp;
@property (nonatomic, getter=time_flag, setter=setTime_flag:) int32_t time_flag;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session time_stamp: (double) time_stamp time_flag: (int32_t) time_flag;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (double) time_stamp;
- (void) setTime_stamp: (double) time_stamp;
#endif
- (BOOL) time_stampIsSet;

#if !__has_feature(objc_arc)
- (int32_t) time_flag;
- (void) setTime_flag: (int32_t) time_flag;
#endif
- (BOOL) time_flagIsSet;

@end

@interface GetFeedResponse : NSObject <TBase, NSCoding> {
  NSMutableArray * __feed_list;

  BOOL __feed_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=feed_list, setter=setFeed_list:) NSMutableArray * feed_list;
#endif

- (id) init;
- (id) initWithFeed_list: (NSMutableArray *) feed_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) feed_list;
- (void) setFeed_list: (NSMutableArray *) feed_list;
#endif
- (BOOL) feed_listIsSet;

@end

@interface DynamicContentPhoto : NSObject <TBase, NSCoding> {
  int64_t __photo_id;
  NSString * __photo_path;
  BOOL __is_cover;

  BOOL __photo_id_isset;
  BOOL __photo_path_isset;
  BOOL __is_cover_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=photo_path, setter=setPhoto_path:) NSString * photo_path;
@property (nonatomic, getter=is_cover, setter=setIs_cover:) BOOL is_cover;
#endif

- (id) init;
- (id) initWithPhoto_id: (int64_t) photo_id photo_path: (NSString *) photo_path is_cover: (BOOL) is_cover;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photo_path;
- (void) setPhoto_path: (NSString *) photo_path;
#endif
- (BOOL) photo_pathIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_cover;
- (void) setIs_cover: (BOOL) is_cover;
#endif
- (BOOL) is_coverIsSet;

@end

@interface DynamicContent : NSObject <TBase, NSCoding> {
  int64_t __content_id;
  int32_t __content_type;
  int64_t __content_user_id;
  NSString * __content_user_name;
  NSString * __content_user_avatar;
  NSString * __content_user_domain;
  NSMutableArray * __photo_list;
  int32_t __photo_count;
  NSString * __content_title;
  NSString * __content_desc;
  int64_t __content_author_id;
  NSString * __content_author_name;
  NSString * __content_author_domain;
  NSString * __create_time;
  BOOL __is_like;
  BOOL __is_recommend;
  BOOL __is_delete;

  BOOL __content_id_isset;
  BOOL __content_type_isset;
  BOOL __content_user_id_isset;
  BOOL __content_user_name_isset;
  BOOL __content_user_avatar_isset;
  BOOL __content_user_domain_isset;
  BOOL __photo_list_isset;
  BOOL __photo_count_isset;
  BOOL __content_title_isset;
  BOOL __content_desc_isset;
  BOOL __content_author_id_isset;
  BOOL __content_author_name_isset;
  BOOL __content_author_domain_isset;
  BOOL __create_time_isset;
  BOOL __is_like_isset;
  BOOL __is_recommend_isset;
  BOOL __is_delete_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=content_id, setter=setContent_id:) int64_t content_id;
@property (nonatomic, getter=content_type, setter=setContent_type:) int32_t content_type;
@property (nonatomic, getter=content_user_id, setter=setContent_user_id:) int64_t content_user_id;
@property (nonatomic, retain, getter=content_user_name, setter=setContent_user_name:) NSString * content_user_name;
@property (nonatomic, retain, getter=content_user_avatar, setter=setContent_user_avatar:) NSString * content_user_avatar;
@property (nonatomic, retain, getter=content_user_domain, setter=setContent_user_domain:) NSString * content_user_domain;
@property (nonatomic, retain, getter=photo_list, setter=setPhoto_list:) NSMutableArray * photo_list;
@property (nonatomic, getter=photo_count, setter=setPhoto_count:) int32_t photo_count;
@property (nonatomic, retain, getter=content_title, setter=setContent_title:) NSString * content_title;
@property (nonatomic, retain, getter=content_desc, setter=setContent_desc:) NSString * content_desc;
@property (nonatomic, getter=content_author_id, setter=setContent_author_id:) int64_t content_author_id;
@property (nonatomic, retain, getter=content_author_name, setter=setContent_author_name:) NSString * content_author_name;
@property (nonatomic, retain, getter=content_author_domain, setter=setContent_author_domain:) NSString * content_author_domain;
@property (nonatomic, retain, getter=create_time, setter=setCreate_time:) NSString * create_time;
@property (nonatomic, getter=is_like, setter=setIs_like:) BOOL is_like;
@property (nonatomic, getter=is_recommend, setter=setIs_recommend:) BOOL is_recommend;
@property (nonatomic, getter=is_delete, setter=setIs_delete:) BOOL is_delete;
#endif

- (id) init;
- (id) initWithContent_id: (int64_t) content_id content_type: (int32_t) content_type content_user_id: (int64_t) content_user_id content_user_name: (NSString *) content_user_name content_user_avatar: (NSString *) content_user_avatar content_user_domain: (NSString *) content_user_domain photo_list: (NSMutableArray *) photo_list photo_count: (int32_t) photo_count content_title: (NSString *) content_title content_desc: (NSString *) content_desc content_author_id: (int64_t) content_author_id content_author_name: (NSString *) content_author_name content_author_domain: (NSString *) content_author_domain create_time: (NSString *) create_time is_like: (BOOL) is_like is_recommend: (BOOL) is_recommend is_delete: (BOOL) is_delete;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) content_id;
- (void) setContent_id: (int64_t) content_id;
#endif
- (BOOL) content_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) content_type;
- (void) setContent_type: (int32_t) content_type;
#endif
- (BOOL) content_typeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) content_user_id;
- (void) setContent_user_id: (int64_t) content_user_id;
#endif
- (BOOL) content_user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_user_name;
- (void) setContent_user_name: (NSString *) content_user_name;
#endif
- (BOOL) content_user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_user_avatar;
- (void) setContent_user_avatar: (NSString *) content_user_avatar;
#endif
- (BOOL) content_user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_user_domain;
- (void) setContent_user_domain: (NSString *) content_user_domain;
#endif
- (BOOL) content_user_domainIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) photo_list;
- (void) setPhoto_list: (NSMutableArray *) photo_list;
#endif
- (BOOL) photo_listIsSet;

#if !__has_feature(objc_arc)
- (int32_t) photo_count;
- (void) setPhoto_count: (int32_t) photo_count;
#endif
- (BOOL) photo_countIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_title;
- (void) setContent_title: (NSString *) content_title;
#endif
- (BOOL) content_titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_desc;
- (void) setContent_desc: (NSString *) content_desc;
#endif
- (BOOL) content_descIsSet;

#if !__has_feature(objc_arc)
- (int64_t) content_author_id;
- (void) setContent_author_id: (int64_t) content_author_id;
#endif
- (BOOL) content_author_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_author_name;
- (void) setContent_author_name: (NSString *) content_author_name;
#endif
- (BOOL) content_author_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content_author_domain;
- (void) setContent_author_domain: (NSString *) content_author_domain;
#endif
- (BOOL) content_author_domainIsSet;

#if !__has_feature(objc_arc)
- (NSString *) create_time;
- (void) setCreate_time: (NSString *) create_time;
#endif
- (BOOL) create_timeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_like;
- (void) setIs_like: (BOOL) is_like;
#endif
- (BOOL) is_likeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_recommend;
- (void) setIs_recommend: (BOOL) is_recommend;
#endif
- (BOOL) is_recommendIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_delete;
- (void) setIs_delete: (BOOL) is_delete;
#endif
- (BOOL) is_deleteIsSet;

@end

@interface GetDynamicListRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __host_domain;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __host_domain_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session host_domain: (NSString *) host_domain page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetDynamicListResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __content_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __content_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=content_list, setter=setContent_list:) NSMutableArray * content_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count content_list: (NSMutableArray *) content_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) content_list;
- (void) setContent_list: (NSMutableArray *) content_list;
#endif
- (BOOL) content_listIsSet;

@end

@interface Album : NSObject <TBase, NSCoding> {
  int64_t __album_id;
  NSString * __album_name;
  int32_t __photo_count;
  NSString * __cover_path;

  BOOL __album_id_isset;
  BOOL __album_name_isset;
  BOOL __photo_count_isset;
  BOOL __cover_path_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=album_id, setter=setAlbum_id:) int64_t album_id;
@property (nonatomic, retain, getter=album_name, setter=setAlbum_name:) NSString * album_name;
@property (nonatomic, getter=photo_count, setter=setPhoto_count:) int32_t photo_count;
@property (nonatomic, retain, getter=cover_path, setter=setCover_path:) NSString * cover_path;
#endif

- (id) init;
- (id) initWithAlbum_id: (int64_t) album_id album_name: (NSString *) album_name photo_count: (int32_t) photo_count cover_path: (NSString *) cover_path;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) album_id;
- (void) setAlbum_id: (int64_t) album_id;
#endif
- (BOOL) album_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) album_name;
- (void) setAlbum_name: (NSString *) album_name;
#endif
- (BOOL) album_nameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) photo_count;
- (void) setPhoto_count: (int32_t) photo_count;
#endif
- (BOOL) photo_countIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cover_path;
- (void) setCover_path: (NSString *) cover_path;
#endif
- (BOOL) cover_pathIsSet;

@end

@interface GetAlbumListRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __host_domain;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __host_domain_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session host_domain: (NSString *) host_domain page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetAlbumListResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __album_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __album_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=album_list, setter=setAlbum_list:) NSMutableArray * album_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count album_list: (NSMutableArray *) album_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) album_list;
- (void) setAlbum_list: (NSMutableArray *) album_list;
#endif
- (BOOL) album_listIsSet;

@end

@interface AlbumPhoto : NSObject <TBase, NSCoding> {
  int64_t __photo_id;
  NSString * __photo_path;
  int32_t __sequence_id;
  BOOL __is_like;

  BOOL __photo_id_isset;
  BOOL __photo_path_isset;
  BOOL __sequence_id_isset;
  BOOL __is_like_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=photo_path, setter=setPhoto_path:) NSString * photo_path;
@property (nonatomic, getter=sequence_id, setter=setSequence_id:) int32_t sequence_id;
@property (nonatomic, getter=is_like, setter=setIs_like:) BOOL is_like;
#endif

- (id) init;
- (id) initWithPhoto_id: (int64_t) photo_id photo_path: (NSString *) photo_path sequence_id: (int32_t) sequence_id is_like: (BOOL) is_like;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photo_path;
- (void) setPhoto_path: (NSString *) photo_path;
#endif
- (BOOL) photo_pathIsSet;

#if !__has_feature(objc_arc)
- (int32_t) sequence_id;
- (void) setSequence_id: (int32_t) sequence_id;
#endif
- (BOOL) sequence_idIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_like;
- (void) setIs_like: (BOOL) is_like;
#endif
- (BOOL) is_likeIsSet;

@end

@interface GetAlbumRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __album_id;

  BOOL __session_isset;
  BOOL __album_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=album_id, setter=setAlbum_id:) int64_t album_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session album_id: (int64_t) album_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) album_id;
- (void) setAlbum_id: (int64_t) album_id;
#endif
- (BOOL) album_idIsSet;

@end

@interface GetAlbumResponse : NSObject <TBase, NSCoding> {
  BOOL __is_self;
  int64_t __album_id;
  NSString * __album_name;
  NSString * __album_desc;
  int32_t __cc_protocol;
  NSString * __create_time;
  NSMutableArray * __tags;
  NSMutableArray * __photo_list;
  NSString * __author_name;
  NSString * __author_domain;
  NSString * __author_avatar;

  BOOL __is_self_isset;
  BOOL __album_id_isset;
  BOOL __album_name_isset;
  BOOL __album_desc_isset;
  BOOL __cc_protocol_isset;
  BOOL __create_time_isset;
  BOOL __tags_isset;
  BOOL __photo_list_isset;
  BOOL __author_name_isset;
  BOOL __author_domain_isset;
  BOOL __author_avatar_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=is_self, setter=setIs_self:) BOOL is_self;
@property (nonatomic, getter=album_id, setter=setAlbum_id:) int64_t album_id;
@property (nonatomic, retain, getter=album_name, setter=setAlbum_name:) NSString * album_name;
@property (nonatomic, retain, getter=album_desc, setter=setAlbum_desc:) NSString * album_desc;
@property (nonatomic, getter=cc_protocol, setter=setCc_protocol:) int32_t cc_protocol;
@property (nonatomic, retain, getter=create_time, setter=setCreate_time:) NSString * create_time;
@property (nonatomic, retain, getter=tags, setter=setTags:) NSMutableArray * tags;
@property (nonatomic, retain, getter=photo_list, setter=setPhoto_list:) NSMutableArray * photo_list;
@property (nonatomic, retain, getter=author_name, setter=setAuthor_name:) NSString * author_name;
@property (nonatomic, retain, getter=author_domain, setter=setAuthor_domain:) NSString * author_domain;
@property (nonatomic, retain, getter=author_avatar, setter=setAuthor_avatar:) NSString * author_avatar;
#endif

- (id) init;
- (id) initWithIs_self: (BOOL) is_self album_id: (int64_t) album_id album_name: (NSString *) album_name album_desc: (NSString *) album_desc cc_protocol: (int32_t) cc_protocol create_time: (NSString *) create_time tags: (NSMutableArray *) tags photo_list: (NSMutableArray *) photo_list author_name: (NSString *) author_name author_domain: (NSString *) author_domain author_avatar: (NSString *) author_avatar;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) is_self;
- (void) setIs_self: (BOOL) is_self;
#endif
- (BOOL) is_selfIsSet;

#if !__has_feature(objc_arc)
- (int64_t) album_id;
- (void) setAlbum_id: (int64_t) album_id;
#endif
- (BOOL) album_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) album_name;
- (void) setAlbum_name: (NSString *) album_name;
#endif
- (BOOL) album_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) album_desc;
- (void) setAlbum_desc: (NSString *) album_desc;
#endif
- (BOOL) album_descIsSet;

#if !__has_feature(objc_arc)
- (int32_t) cc_protocol;
- (void) setCc_protocol: (int32_t) cc_protocol;
#endif
- (BOOL) cc_protocolIsSet;

#if !__has_feature(objc_arc)
- (NSString *) create_time;
- (void) setCreate_time: (NSString *) create_time;
#endif
- (BOOL) create_timeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tags;
- (void) setTags: (NSMutableArray *) tags;
#endif
- (BOOL) tagsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) photo_list;
- (void) setPhoto_list: (NSMutableArray *) photo_list;
#endif
- (BOOL) photo_listIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_name;
- (void) setAuthor_name: (NSString *) author_name;
#endif
- (BOOL) author_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_domain;
- (void) setAuthor_domain: (NSString *) author_domain;
#endif
- (BOOL) author_domainIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_avatar;
- (void) setAuthor_avatar: (NSString *) author_avatar;
#endif
- (BOOL) author_avatarIsSet;

@end

@interface Photo : NSObject <TBase, NSCoding> {
  int64_t __photo_id;
  NSString * __photo_path;
  int32_t __sequence_id;
  int32_t __temperature;
  BOOL __is_like;
  BOOL __is_favorite;
  BOOL __is_recommend;

  BOOL __photo_id_isset;
  BOOL __photo_path_isset;
  BOOL __sequence_id_isset;
  BOOL __temperature_isset;
  BOOL __is_like_isset;
  BOOL __is_favorite_isset;
  BOOL __is_recommend_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=photo_path, setter=setPhoto_path:) NSString * photo_path;
@property (nonatomic, getter=sequence_id, setter=setSequence_id:) int32_t sequence_id;
@property (nonatomic, getter=temperature, setter=setTemperature:) int32_t temperature;
@property (nonatomic, getter=is_like, setter=setIs_like:) BOOL is_like;
@property (nonatomic, getter=is_favorite, setter=setIs_favorite:) BOOL is_favorite;
@property (nonatomic, getter=is_recommend, setter=setIs_recommend:) BOOL is_recommend;
#endif

- (id) init;
- (id) initWithPhoto_id: (int64_t) photo_id photo_path: (NSString *) photo_path sequence_id: (int32_t) sequence_id temperature: (int32_t) temperature is_like: (BOOL) is_like is_favorite: (BOOL) is_favorite is_recommend: (BOOL) is_recommend;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photo_path;
- (void) setPhoto_path: (NSString *) photo_path;
#endif
- (BOOL) photo_pathIsSet;

#if !__has_feature(objc_arc)
- (int32_t) sequence_id;
- (void) setSequence_id: (int32_t) sequence_id;
#endif
- (BOOL) sequence_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) temperature;
- (void) setTemperature: (int32_t) temperature;
#endif
- (BOOL) temperatureIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_like;
- (void) setIs_like: (BOOL) is_like;
#endif
- (BOOL) is_likeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_favorite;
- (void) setIs_favorite: (BOOL) is_favorite;
#endif
- (BOOL) is_favoriteIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_recommend;
- (void) setIs_recommend: (BOOL) is_recommend;
#endif
- (BOOL) is_recommendIsSet;

@end

@interface GetPhotoRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;

  BOOL __session_isset;
  BOOL __photo_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

@end

@interface GetPhotoResponse : NSObject <TBase, NSCoding> {
  int64_t __photo_id;
  NSString * __photo_path;
  int64_t __album_id;
  NSString * __album_name;
  int64_t __author_id;
  NSString * __author_name;
  NSString * __author_avatar;
  NSString * __author_domain;
  int32_t __cc_protocol;
  NSMutableArray * __photo_list;

  BOOL __photo_id_isset;
  BOOL __photo_path_isset;
  BOOL __album_id_isset;
  BOOL __album_name_isset;
  BOOL __author_id_isset;
  BOOL __author_name_isset;
  BOOL __author_avatar_isset;
  BOOL __author_domain_isset;
  BOOL __cc_protocol_isset;
  BOOL __photo_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=photo_path, setter=setPhoto_path:) NSString * photo_path;
@property (nonatomic, getter=album_id, setter=setAlbum_id:) int64_t album_id;
@property (nonatomic, retain, getter=album_name, setter=setAlbum_name:) NSString * album_name;
@property (nonatomic, getter=author_id, setter=setAuthor_id:) int64_t author_id;
@property (nonatomic, retain, getter=author_name, setter=setAuthor_name:) NSString * author_name;
@property (nonatomic, retain, getter=author_avatar, setter=setAuthor_avatar:) NSString * author_avatar;
@property (nonatomic, retain, getter=author_domain, setter=setAuthor_domain:) NSString * author_domain;
@property (nonatomic, getter=cc_protocol, setter=setCc_protocol:) int32_t cc_protocol;
@property (nonatomic, retain, getter=photo_list, setter=setPhoto_list:) NSMutableArray * photo_list;
#endif

- (id) init;
- (id) initWithPhoto_id: (int64_t) photo_id photo_path: (NSString *) photo_path album_id: (int64_t) album_id album_name: (NSString *) album_name author_id: (int64_t) author_id author_name: (NSString *) author_name author_avatar: (NSString *) author_avatar author_domain: (NSString *) author_domain cc_protocol: (int32_t) cc_protocol photo_list: (NSMutableArray *) photo_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photo_path;
- (void) setPhoto_path: (NSString *) photo_path;
#endif
- (BOOL) photo_pathIsSet;

#if !__has_feature(objc_arc)
- (int64_t) album_id;
- (void) setAlbum_id: (int64_t) album_id;
#endif
- (BOOL) album_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) album_name;
- (void) setAlbum_name: (NSString *) album_name;
#endif
- (BOOL) album_nameIsSet;

#if !__has_feature(objc_arc)
- (int64_t) author_id;
- (void) setAuthor_id: (int64_t) author_id;
#endif
- (BOOL) author_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_name;
- (void) setAuthor_name: (NSString *) author_name;
#endif
- (BOOL) author_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_avatar;
- (void) setAuthor_avatar: (NSString *) author_avatar;
#endif
- (BOOL) author_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_domain;
- (void) setAuthor_domain: (NSString *) author_domain;
#endif
- (BOOL) author_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) cc_protocol;
- (void) setCc_protocol: (int32_t) cc_protocol;
#endif
- (BOOL) cc_protocolIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) photo_list;
- (void) setPhoto_list: (NSMutableArray *) photo_list;
#endif
- (BOOL) photo_listIsSet;

@end

@interface RecommendPhoto : NSObject <TBase, NSCoding> {
  int64_t __photo_id;
  NSString * __photo_path;

  BOOL __photo_id_isset;
  BOOL __photo_path_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=photo_path, setter=setPhoto_path:) NSString * photo_path;
#endif

- (id) init;
- (id) initWithPhoto_id: (int64_t) photo_id photo_path: (NSString *) photo_path;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photo_path;
- (void) setPhoto_path: (NSString *) photo_path;
#endif
- (BOOL) photo_pathIsSet;

@end

@interface GetPhotoRecommendRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __album_id;

  BOOL __session_isset;
  BOOL __album_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=album_id, setter=setAlbum_id:) int64_t album_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session album_id: (int64_t) album_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) album_id;
- (void) setAlbum_id: (int64_t) album_id;
#endif
- (BOOL) album_idIsSet;

@end

@interface GetPhotoRecommendResponse : NSObject <TBase, NSCoding> {
  NSMutableArray * __photo_list;

  BOOL __photo_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=photo_list, setter=setPhoto_list:) NSMutableArray * photo_list;
#endif

- (id) init;
- (id) initWithPhoto_list: (NSMutableArray *) photo_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) photo_list;
- (void) setPhoto_list: (NSMutableArray *) photo_list;
#endif
- (BOOL) photo_listIsSet;

@end

@interface Comment : NSObject <TBase, NSCoding> {
  int64_t __comment_id;
  NSString * __comment_text;
  int64_t __comment_user_id;
  NSString * __comment_user_name;
  NSString * __comment_user_avatar;
  NSString * __comment_user_domain;
  int64_t __reply_user_id;
  NSString * __reply_user_name;
  NSString * __reply_user_domain;
  NSString * __create_time;
  BOOL __is_self;

  BOOL __comment_id_isset;
  BOOL __comment_text_isset;
  BOOL __comment_user_id_isset;
  BOOL __comment_user_name_isset;
  BOOL __comment_user_avatar_isset;
  BOOL __comment_user_domain_isset;
  BOOL __reply_user_id_isset;
  BOOL __reply_user_name_isset;
  BOOL __reply_user_domain_isset;
  BOOL __create_time_isset;
  BOOL __is_self_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=comment_id, setter=setComment_id:) int64_t comment_id;
@property (nonatomic, retain, getter=comment_text, setter=setComment_text:) NSString * comment_text;
@property (nonatomic, getter=comment_user_id, setter=setComment_user_id:) int64_t comment_user_id;
@property (nonatomic, retain, getter=comment_user_name, setter=setComment_user_name:) NSString * comment_user_name;
@property (nonatomic, retain, getter=comment_user_avatar, setter=setComment_user_avatar:) NSString * comment_user_avatar;
@property (nonatomic, retain, getter=comment_user_domain, setter=setComment_user_domain:) NSString * comment_user_domain;
@property (nonatomic, getter=reply_user_id, setter=setReply_user_id:) int64_t reply_user_id;
@property (nonatomic, retain, getter=reply_user_name, setter=setReply_user_name:) NSString * reply_user_name;
@property (nonatomic, retain, getter=reply_user_domain, setter=setReply_user_domain:) NSString * reply_user_domain;
@property (nonatomic, retain, getter=create_time, setter=setCreate_time:) NSString * create_time;
@property (nonatomic, getter=is_self, setter=setIs_self:) BOOL is_self;
#endif

- (id) init;
- (id) initWithComment_id: (int64_t) comment_id comment_text: (NSString *) comment_text comment_user_id: (int64_t) comment_user_id comment_user_name: (NSString *) comment_user_name comment_user_avatar: (NSString *) comment_user_avatar comment_user_domain: (NSString *) comment_user_domain reply_user_id: (int64_t) reply_user_id reply_user_name: (NSString *) reply_user_name reply_user_domain: (NSString *) reply_user_domain create_time: (NSString *) create_time is_self: (BOOL) is_self;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) comment_id;
- (void) setComment_id: (int64_t) comment_id;
#endif
- (BOOL) comment_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment_text;
- (void) setComment_text: (NSString *) comment_text;
#endif
- (BOOL) comment_textIsSet;

#if !__has_feature(objc_arc)
- (int64_t) comment_user_id;
- (void) setComment_user_id: (int64_t) comment_user_id;
#endif
- (BOOL) comment_user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment_user_name;
- (void) setComment_user_name: (NSString *) comment_user_name;
#endif
- (BOOL) comment_user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment_user_avatar;
- (void) setComment_user_avatar: (NSString *) comment_user_avatar;
#endif
- (BOOL) comment_user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment_user_domain;
- (void) setComment_user_domain: (NSString *) comment_user_domain;
#endif
- (BOOL) comment_user_domainIsSet;

#if !__has_feature(objc_arc)
- (int64_t) reply_user_id;
- (void) setReply_user_id: (int64_t) reply_user_id;
#endif
- (BOOL) reply_user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reply_user_name;
- (void) setReply_user_name: (NSString *) reply_user_name;
#endif
- (BOOL) reply_user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reply_user_domain;
- (void) setReply_user_domain: (NSString *) reply_user_domain;
#endif
- (BOOL) reply_user_domainIsSet;

#if !__has_feature(objc_arc)
- (NSString *) create_time;
- (void) setCreate_time: (NSString *) create_time;
#endif
- (BOOL) create_timeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_self;
- (void) setIs_self: (BOOL) is_self;
#endif
- (BOOL) is_selfIsSet;

@end

@interface GetPhotoCommentRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __photo_id_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetPhotoCommentResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  NSMutableArray * __comment_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __comment_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, retain, getter=comment_list, setter=setComment_list:) NSMutableArray * comment_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size comment_list: (NSMutableArray *) comment_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) comment_list;
- (void) setComment_list: (NSMutableArray *) comment_list;
#endif
- (BOOL) comment_listIsSet;

@end

@interface AddPhotoCommentRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __reply_user_id;
  int64_t __photo_id;
  NSString * __comment_text;

  BOOL __session_isset;
  BOOL __reply_user_id_isset;
  BOOL __photo_id_isset;
  BOOL __comment_text_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=reply_user_id, setter=setReply_user_id:) int64_t reply_user_id;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=comment_text, setter=setComment_text:) NSString * comment_text;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session reply_user_id: (int64_t) reply_user_id photo_id: (int64_t) photo_id comment_text: (NSString *) comment_text;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) reply_user_id;
- (void) setReply_user_id: (int64_t) reply_user_id;
#endif
- (BOOL) reply_user_idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment_text;
- (void) setComment_text: (NSString *) comment_text;
#endif
- (BOOL) comment_textIsSet;

@end

@interface AddPhotoCommentResponse : NSObject <TBase, NSCoding> {
  Comment * __comment;

  BOOL __comment_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=comment, setter=setComment:) Comment * comment;
#endif

- (id) init;
- (id) initWithComment: (Comment *) comment;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Comment *) comment;
- (void) setComment: (Comment *) comment;
#endif
- (BOOL) commentIsSet;

@end

@interface DeletePhotoCommentRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;
  int64_t __comment_id;

  BOOL __session_isset;
  BOOL __photo_id_isset;
  BOOL __comment_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, getter=comment_id, setter=setComment_id:) int64_t comment_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id comment_id: (int64_t) comment_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) comment_id;
- (void) setComment_id: (int64_t) comment_id;
#endif
- (BOOL) comment_idIsSet;

@end

@interface Pocket : NSObject <TBase, NSCoding> {
  int64_t __pocket_id;
  NSString * __pocket_title;
  NSString * __pocket_second_title;
  NSString * __cover_photo;
  NSString * __create_time;
  BOOL __is_like;
  BOOL __is_recommend;

  BOOL __pocket_id_isset;
  BOOL __pocket_title_isset;
  BOOL __pocket_second_title_isset;
  BOOL __cover_photo_isset;
  BOOL __create_time_isset;
  BOOL __is_like_isset;
  BOOL __is_recommend_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
@property (nonatomic, retain, getter=pocket_title, setter=setPocket_title:) NSString * pocket_title;
@property (nonatomic, retain, getter=pocket_second_title, setter=setPocket_second_title:) NSString * pocket_second_title;
@property (nonatomic, retain, getter=cover_photo, setter=setCover_photo:) NSString * cover_photo;
@property (nonatomic, retain, getter=create_time, setter=setCreate_time:) NSString * create_time;
@property (nonatomic, getter=is_like, setter=setIs_like:) BOOL is_like;
@property (nonatomic, getter=is_recommend, setter=setIs_recommend:) BOOL is_recommend;
#endif

- (id) init;
- (id) initWithPocket_id: (int64_t) pocket_id pocket_title: (NSString *) pocket_title pocket_second_title: (NSString *) pocket_second_title cover_photo: (NSString *) cover_photo create_time: (NSString *) create_time is_like: (BOOL) is_like is_recommend: (BOOL) is_recommend;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_title;
- (void) setPocket_title: (NSString *) pocket_title;
#endif
- (BOOL) pocket_titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_second_title;
- (void) setPocket_second_title: (NSString *) pocket_second_title;
#endif
- (BOOL) pocket_second_titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cover_photo;
- (void) setCover_photo: (NSString *) cover_photo;
#endif
- (BOOL) cover_photoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) create_time;
- (void) setCreate_time: (NSString *) create_time;
#endif
- (BOOL) create_timeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_like;
- (void) setIs_like: (BOOL) is_like;
#endif
- (BOOL) is_likeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_recommend;
- (void) setIs_recommend: (BOOL) is_recommend;
#endif
- (BOOL) is_recommendIsSet;

@end

@interface GetPocketListRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __host_domain;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __host_domain_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session host_domain: (NSString *) host_domain page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetPocketListResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __pocket_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __pocket_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=pocket_list, setter=setPocket_list:) NSMutableArray * pocket_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count pocket_list: (NSMutableArray *) pocket_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) pocket_list;
- (void) setPocket_list: (NSMutableArray *) pocket_list;
#endif
- (BOOL) pocket_listIsSet;

@end

@interface GetPocketRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

@end

@interface GetPocketResponse : NSObject <TBase, NSCoding> {
  int64_t __pocket_id;
  NSString * __pocket_cover_photo;
  NSString * __pocket_title;
  NSString * __pocket_second_title;
  NSString * __pocket_content;
  NSString * __create_time;
  int64_t __author_id;
  NSString * __author_name;
  NSString * __author_avatar;
  NSString * __author_domain;
  int32_t __temperature;
  BOOL __is_self;
  int32_t __follow_state;
  BOOL __is_like;
  BOOL __is_favorite;
  BOOL __is_recommend;

  BOOL __pocket_id_isset;
  BOOL __pocket_cover_photo_isset;
  BOOL __pocket_title_isset;
  BOOL __pocket_second_title_isset;
  BOOL __pocket_content_isset;
  BOOL __create_time_isset;
  BOOL __author_id_isset;
  BOOL __author_name_isset;
  BOOL __author_avatar_isset;
  BOOL __author_domain_isset;
  BOOL __temperature_isset;
  BOOL __is_self_isset;
  BOOL __follow_state_isset;
  BOOL __is_like_isset;
  BOOL __is_favorite_isset;
  BOOL __is_recommend_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
@property (nonatomic, retain, getter=pocket_cover_photo, setter=setPocket_cover_photo:) NSString * pocket_cover_photo;
@property (nonatomic, retain, getter=pocket_title, setter=setPocket_title:) NSString * pocket_title;
@property (nonatomic, retain, getter=pocket_second_title, setter=setPocket_second_title:) NSString * pocket_second_title;
@property (nonatomic, retain, getter=pocket_content, setter=setPocket_content:) NSString * pocket_content;
@property (nonatomic, retain, getter=create_time, setter=setCreate_time:) NSString * create_time;
@property (nonatomic, getter=author_id, setter=setAuthor_id:) int64_t author_id;
@property (nonatomic, retain, getter=author_name, setter=setAuthor_name:) NSString * author_name;
@property (nonatomic, retain, getter=author_avatar, setter=setAuthor_avatar:) NSString * author_avatar;
@property (nonatomic, retain, getter=author_domain, setter=setAuthor_domain:) NSString * author_domain;
@property (nonatomic, getter=temperature, setter=setTemperature:) int32_t temperature;
@property (nonatomic, getter=is_self, setter=setIs_self:) BOOL is_self;
@property (nonatomic, getter=follow_state, setter=setFollow_state:) int32_t follow_state;
@property (nonatomic, getter=is_like, setter=setIs_like:) BOOL is_like;
@property (nonatomic, getter=is_favorite, setter=setIs_favorite:) BOOL is_favorite;
@property (nonatomic, getter=is_recommend, setter=setIs_recommend:) BOOL is_recommend;
#endif

- (id) init;
- (id) initWithPocket_id: (int64_t) pocket_id pocket_cover_photo: (NSString *) pocket_cover_photo pocket_title: (NSString *) pocket_title pocket_second_title: (NSString *) pocket_second_title pocket_content: (NSString *) pocket_content create_time: (NSString *) create_time author_id: (int64_t) author_id author_name: (NSString *) author_name author_avatar: (NSString *) author_avatar author_domain: (NSString *) author_domain temperature: (int32_t) temperature is_self: (BOOL) is_self follow_state: (int32_t) follow_state is_like: (BOOL) is_like is_favorite: (BOOL) is_favorite is_recommend: (BOOL) is_recommend;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_cover_photo;
- (void) setPocket_cover_photo: (NSString *) pocket_cover_photo;
#endif
- (BOOL) pocket_cover_photoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_title;
- (void) setPocket_title: (NSString *) pocket_title;
#endif
- (BOOL) pocket_titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_second_title;
- (void) setPocket_second_title: (NSString *) pocket_second_title;
#endif
- (BOOL) pocket_second_titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pocket_content;
- (void) setPocket_content: (NSString *) pocket_content;
#endif
- (BOOL) pocket_contentIsSet;

#if !__has_feature(objc_arc)
- (NSString *) create_time;
- (void) setCreate_time: (NSString *) create_time;
#endif
- (BOOL) create_timeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) author_id;
- (void) setAuthor_id: (int64_t) author_id;
#endif
- (BOOL) author_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_name;
- (void) setAuthor_name: (NSString *) author_name;
#endif
- (BOOL) author_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_avatar;
- (void) setAuthor_avatar: (NSString *) author_avatar;
#endif
- (BOOL) author_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_domain;
- (void) setAuthor_domain: (NSString *) author_domain;
#endif
- (BOOL) author_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) temperature;
- (void) setTemperature: (int32_t) temperature;
#endif
- (BOOL) temperatureIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_self;
- (void) setIs_self: (BOOL) is_self;
#endif
- (BOOL) is_selfIsSet;

#if !__has_feature(objc_arc)
- (int32_t) follow_state;
- (void) setFollow_state: (int32_t) follow_state;
#endif
- (BOOL) follow_stateIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_like;
- (void) setIs_like: (BOOL) is_like;
#endif
- (BOOL) is_likeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_favorite;
- (void) setIs_favorite: (BOOL) is_favorite;
#endif
- (BOOL) is_favoriteIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_recommend;
- (void) setIs_recommend: (BOOL) is_recommend;
#endif
- (BOOL) is_recommendIsSet;

@end

@interface GetPocketCommentRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetPocketCommentResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  NSMutableArray * __comment_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __comment_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, retain, getter=comment_list, setter=setComment_list:) NSMutableArray * comment_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size comment_list: (NSMutableArray *) comment_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) comment_list;
- (void) setComment_list: (NSMutableArray *) comment_list;
#endif
- (BOOL) comment_listIsSet;

@end

@interface AddPocketCommentRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __reply_user_id;
  int64_t __pocket_id;
  NSString * __comment_text;

  BOOL __session_isset;
  BOOL __reply_user_id_isset;
  BOOL __pocket_id_isset;
  BOOL __comment_text_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=reply_user_id, setter=setReply_user_id:) int64_t reply_user_id;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
@property (nonatomic, retain, getter=comment_text, setter=setComment_text:) NSString * comment_text;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session reply_user_id: (int64_t) reply_user_id pocket_id: (int64_t) pocket_id comment_text: (NSString *) comment_text;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) reply_user_id;
- (void) setReply_user_id: (int64_t) reply_user_id;
#endif
- (BOOL) reply_user_idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment_text;
- (void) setComment_text: (NSString *) comment_text;
#endif
- (BOOL) comment_textIsSet;

@end

@interface AddPocketCommentResponse : NSObject <TBase, NSCoding> {
  Comment * __comment;

  BOOL __comment_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=comment, setter=setComment:) Comment * comment;
#endif

- (id) init;
- (id) initWithComment: (Comment *) comment;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Comment *) comment;
- (void) setComment: (Comment *) comment;
#endif
- (BOOL) commentIsSet;

@end

@interface DeletePocketCommentRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;
  int64_t __comment_id;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
  BOOL __comment_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
@property (nonatomic, getter=comment_id, setter=setComment_id:) int64_t comment_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id comment_id: (int64_t) comment_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) comment_id;
- (void) setComment_id: (int64_t) comment_id;
#endif
- (BOOL) comment_idIsSet;

@end

@interface contentConstants : NSObject {
}
@end
