/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface SearchPhoto : NSObject <TBase, NSCoding> {
  int64_t __photo_id;
  NSString * __photo_path;
  BOOL __is_like;
  NSString * __author_name;
  NSString * __author_domain;

  BOOL __photo_id_isset;
  BOOL __photo_path_isset;
  BOOL __is_like_isset;
  BOOL __author_name_isset;
  BOOL __author_domain_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
@property (nonatomic, retain, getter=photo_path, setter=setPhoto_path:) NSString * photo_path;
@property (nonatomic, getter=is_like, setter=setIs_like:) BOOL is_like;
@property (nonatomic, retain, getter=author_name, setter=setAuthor_name:) NSString * author_name;
@property (nonatomic, retain, getter=author_domain, setter=setAuthor_domain:) NSString * author_domain;
#endif

- (id) init;
- (id) initWithPhoto_id: (int64_t) photo_id photo_path: (NSString *) photo_path is_like: (BOOL) is_like author_name: (NSString *) author_name author_domain: (NSString *) author_domain;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photo_path;
- (void) setPhoto_path: (NSString *) photo_path;
#endif
- (BOOL) photo_pathIsSet;

#if !__has_feature(objc_arc)
- (BOOL) is_like;
- (void) setIs_like: (BOOL) is_like;
#endif
- (BOOL) is_likeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_name;
- (void) setAuthor_name: (NSString *) author_name;
#endif
- (BOOL) author_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author_domain;
- (void) setAuthor_domain: (NSString *) author_domain;
#endif
- (BOOL) author_domainIsSet;

@end

@interface SearchPhotoRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int32_t __page_no;
  int32_t __page_size;
  NSMutableArray * __tags;

  BOOL __session_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __tags_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, retain, getter=tags, setter=setTags:) NSMutableArray * tags;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session page_no: (int32_t) page_no page_size: (int32_t) page_size tags: (NSMutableArray *) tags;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tags;
- (void) setTags: (NSMutableArray *) tags;
#endif
- (BOOL) tagsIsSet;

@end

@interface SearchPhotoResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __photo_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __photo_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=photo_list, setter=setPhoto_list:) NSMutableArray * photo_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count photo_list: (NSMutableArray *) photo_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) photo_list;
- (void) setPhoto_list: (NSMutableArray *) photo_list;
#endif
- (BOOL) photo_listIsSet;

@end

@interface SearchUser : NSObject <TBase, NSCoding> {
  int64_t __user_id;
  NSString * __user_name;
  NSString * __user_desc;
  NSString * __avatar;
  NSString * __domain;
  int32_t __gender;
  NSString * __address;
  int32_t __follow_state;

  BOOL __user_id_isset;
  BOOL __user_name_isset;
  BOOL __user_desc_isset;
  BOOL __avatar_isset;
  BOOL __domain_isset;
  BOOL __gender_isset;
  BOOL __address_isset;
  BOOL __follow_state_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_desc, setter=setUser_desc:) NSString * user_desc;
@property (nonatomic, retain, getter=avatar, setter=setAvatar:) NSString * avatar;
@property (nonatomic, retain, getter=domain, setter=setDomain:) NSString * domain;
@property (nonatomic, getter=gender, setter=setGender:) int32_t gender;
@property (nonatomic, retain, getter=address, setter=setAddress:) NSString * address;
@property (nonatomic, getter=follow_state, setter=setFollow_state:) int32_t follow_state;
#endif

- (id) init;
- (id) initWithUser_id: (int64_t) user_id user_name: (NSString *) user_name user_desc: (NSString *) user_desc avatar: (NSString *) avatar domain: (NSString *) domain gender: (int32_t) gender address: (NSString *) address follow_state: (int32_t) follow_state;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
#endif
- (BOOL) user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_desc;
- (void) setUser_desc: (NSString *) user_desc;
#endif
- (BOOL) user_descIsSet;

#if !__has_feature(objc_arc)
- (NSString *) avatar;
- (void) setAvatar: (NSString *) avatar;
#endif
- (BOOL) avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) domain;
- (void) setDomain: (NSString *) domain;
#endif
- (BOOL) domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gender;
- (void) setGender: (int32_t) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address;
- (void) setAddress: (NSString *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (int32_t) follow_state;
- (void) setFollow_state: (int32_t) follow_state;
#endif
- (BOOL) follow_stateIsSet;

@end

@interface SearchUserRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int32_t __page_no;
  int32_t __page_size;
  NSMutableArray * __tags;

  BOOL __session_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __tags_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, retain, getter=tags, setter=setTags:) NSMutableArray * tags;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session page_no: (int32_t) page_no page_size: (int32_t) page_size tags: (NSMutableArray *) tags;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tags;
- (void) setTags: (NSMutableArray *) tags;
#endif
- (BOOL) tagsIsSet;

@end

@interface SearchUserResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __user_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __user_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=user_list, setter=setUser_list:) NSMutableArray * user_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count user_list: (NSMutableArray *) user_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) user_list;
- (void) setUser_list: (NSMutableArray *) user_list;
#endif
- (BOOL) user_listIsSet;

@end

@interface HotSearchRequest : NSObject <TBase, NSCoding> {
  NSString * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface HotSearchResponse : NSObject <TBase, NSCoding> {
  NSMutableArray * __tags;

  BOOL __tags_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=tags, setter=setTags:) NSMutableArray * tags;
#endif

- (id) init;
- (id) initWithTags: (NSMutableArray *) tags;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tags;
- (void) setTags: (NSMutableArray *) tags;
#endif
- (BOOL) tagsIsSet;

@end

@interface searchConstants : NSObject {
}
@end
