/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface GetHomeRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __host_domain;

  BOOL __session_isset;
  BOOL __host_domain_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session host_domain: (NSString *) host_domain;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

@end

@interface GetHomeResponse : NSObject <TBase, NSCoding> {
  BOOL __is_self;
  int64_t __host_id;
  NSString * __host_name;
  NSString * __host_avatar;
  NSString * __host_domain;
  NSString * __host_desc;
  int32_t __host_gender;
  NSString * __banner_photo;
  int32_t __dynamic_count;
  int32_t __follow_count;
  int32_t __follower_count;
  int32_t __follow_state;
  NSString * __address;
  int32_t __gift;
  int32_t __photograph_type;
  NSMutableArray * __photograph_address;

  BOOL __is_self_isset;
  BOOL __host_id_isset;
  BOOL __host_name_isset;
  BOOL __host_avatar_isset;
  BOOL __host_domain_isset;
  BOOL __host_desc_isset;
  BOOL __host_gender_isset;
  BOOL __banner_photo_isset;
  BOOL __dynamic_count_isset;
  BOOL __follow_count_isset;
  BOOL __follower_count_isset;
  BOOL __follow_state_isset;
  BOOL __address_isset;
  BOOL __gift_isset;
  BOOL __photograph_type_isset;
  BOOL __photograph_address_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=is_self, setter=setIs_self:) BOOL is_self;
@property (nonatomic, getter=host_id, setter=setHost_id:) int64_t host_id;
@property (nonatomic, retain, getter=host_name, setter=setHost_name:) NSString * host_name;
@property (nonatomic, retain, getter=host_avatar, setter=setHost_avatar:) NSString * host_avatar;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
@property (nonatomic, retain, getter=host_desc, setter=setHost_desc:) NSString * host_desc;
@property (nonatomic, getter=host_gender, setter=setHost_gender:) int32_t host_gender;
@property (nonatomic, retain, getter=banner_photo, setter=setBanner_photo:) NSString * banner_photo;
@property (nonatomic, getter=dynamic_count, setter=setDynamic_count:) int32_t dynamic_count;
@property (nonatomic, getter=follow_count, setter=setFollow_count:) int32_t follow_count;
@property (nonatomic, getter=follower_count, setter=setFollower_count:) int32_t follower_count;
@property (nonatomic, getter=follow_state, setter=setFollow_state:) int32_t follow_state;
@property (nonatomic, retain, getter=address, setter=setAddress:) NSString * address;
@property (nonatomic, getter=gift, setter=setGift:) int32_t gift;
@property (nonatomic, getter=photograph_type, setter=setPhotograph_type:) int32_t photograph_type;
@property (nonatomic, retain, getter=photograph_address, setter=setPhotograph_address:) NSMutableArray * photograph_address;
#endif

- (id) init;
- (id) initWithIs_self: (BOOL) is_self host_id: (int64_t) host_id host_name: (NSString *) host_name host_avatar: (NSString *) host_avatar host_domain: (NSString *) host_domain host_desc: (NSString *) host_desc host_gender: (int32_t) host_gender banner_photo: (NSString *) banner_photo dynamic_count: (int32_t) dynamic_count follow_count: (int32_t) follow_count follower_count: (int32_t) follower_count follow_state: (int32_t) follow_state address: (NSString *) address gift: (int32_t) gift photograph_type: (int32_t) photograph_type photograph_address: (NSMutableArray *) photograph_address;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) is_self;
- (void) setIs_self: (BOOL) is_self;
#endif
- (BOOL) is_selfIsSet;

#if !__has_feature(objc_arc)
- (int64_t) host_id;
- (void) setHost_id: (int64_t) host_id;
#endif
- (BOOL) host_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_name;
- (void) setHost_name: (NSString *) host_name;
#endif
- (BOOL) host_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_avatar;
- (void) setHost_avatar: (NSString *) host_avatar;
#endif
- (BOOL) host_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_desc;
- (void) setHost_desc: (NSString *) host_desc;
#endif
- (BOOL) host_descIsSet;

#if !__has_feature(objc_arc)
- (int32_t) host_gender;
- (void) setHost_gender: (int32_t) host_gender;
#endif
- (BOOL) host_genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) banner_photo;
- (void) setBanner_photo: (NSString *) banner_photo;
#endif
- (BOOL) banner_photoIsSet;

#if !__has_feature(objc_arc)
- (int32_t) dynamic_count;
- (void) setDynamic_count: (int32_t) dynamic_count;
#endif
- (BOOL) dynamic_countIsSet;

#if !__has_feature(objc_arc)
- (int32_t) follow_count;
- (void) setFollow_count: (int32_t) follow_count;
#endif
- (BOOL) follow_countIsSet;

#if !__has_feature(objc_arc)
- (int32_t) follower_count;
- (void) setFollower_count: (int32_t) follower_count;
#endif
- (BOOL) follower_countIsSet;

#if !__has_feature(objc_arc)
- (int32_t) follow_state;
- (void) setFollow_state: (int32_t) follow_state;
#endif
- (BOOL) follow_stateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address;
- (void) setAddress: (NSString *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gift;
- (void) setGift: (int32_t) gift;
#endif
- (BOOL) giftIsSet;

#if !__has_feature(objc_arc)
- (int32_t) photograph_type;
- (void) setPhotograph_type: (int32_t) photograph_type;
#endif
- (BOOL) photograph_typeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) photograph_address;
- (void) setPhotograph_address: (NSMutableArray *) photograph_address;
#endif
- (BOOL) photograph_addressIsSet;

@end

@interface GetTopUserRequest : NSObject <TBase, NSCoding> {
  NSString * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface GetTopUserResponse : NSObject <TBase, NSCoding> {
  int32_t __gift;
  NSString * __user_name;
  NSString * __user_avatar;
  NSString * __user_domain;

  BOOL __gift_isset;
  BOOL __user_name_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=gift, setter=setGift:) int32_t gift;
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
#endif

- (id) init;
- (id) initWithGift: (int32_t) gift user_name: (NSString *) user_name user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) gift;
- (void) setGift: (int32_t) gift;
#endif
- (BOOL) giftIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

@end

@interface FollowRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __follow_id;

  BOOL __session_isset;
  BOOL __follow_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=follow_id, setter=setFollow_id:) int64_t follow_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session follow_id: (int64_t) follow_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) follow_id;
- (void) setFollow_id: (int64_t) follow_id;
#endif
- (BOOL) follow_idIsSet;

@end

@interface FollowResponse : NSObject <TBase, NSCoding> {
  int32_t __follow_state;

  BOOL __follow_state_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=follow_state, setter=setFollow_state:) int32_t follow_state;
#endif

- (id) init;
- (id) initWithFollow_state: (int32_t) follow_state;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) follow_state;
- (void) setFollow_state: (int32_t) follow_state;
#endif
- (BOOL) follow_stateIsSet;

@end

@interface UnFollowRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __follow_id;

  BOOL __session_isset;
  BOOL __follow_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=follow_id, setter=setFollow_id:) int64_t follow_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session follow_id: (int64_t) follow_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) follow_id;
- (void) setFollow_id: (int64_t) follow_id;
#endif
- (BOOL) follow_idIsSet;

@end

@interface UnFollowResponse : NSObject <TBase, NSCoding> {
  int32_t __follow_state;

  BOOL __follow_state_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=follow_state, setter=setFollow_state:) int32_t follow_state;
#endif

- (id) init;
- (id) initWithFollow_state: (int32_t) follow_state;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) follow_state;
- (void) setFollow_state: (int32_t) follow_state;
#endif
- (BOOL) follow_stateIsSet;

@end

@interface FollowUser : NSObject <TBase, NSCoding> {
  int64_t __user_id;
  NSString * __user_name;
  NSString * __user_desc;
  NSString * __user_avatar;
  NSString * __user_domain;
  int32_t __user_gender;
  NSString * __user_address;
  int32_t __follow_state;
  NSString * __follow_date;

  BOOL __user_id_isset;
  BOOL __user_name_isset;
  BOOL __user_desc_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
  BOOL __user_gender_isset;
  BOOL __user_address_isset;
  BOOL __follow_state_isset;
  BOOL __follow_date_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_desc, setter=setUser_desc:) NSString * user_desc;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
@property (nonatomic, getter=user_gender, setter=setUser_gender:) int32_t user_gender;
@property (nonatomic, retain, getter=user_address, setter=setUser_address:) NSString * user_address;
@property (nonatomic, getter=follow_state, setter=setFollow_state:) int32_t follow_state;
@property (nonatomic, retain, getter=follow_date, setter=setFollow_date:) NSString * follow_date;
#endif

- (id) init;
- (id) initWithUser_id: (int64_t) user_id user_name: (NSString *) user_name user_desc: (NSString *) user_desc user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain user_gender: (int32_t) user_gender user_address: (NSString *) user_address follow_state: (int32_t) follow_state follow_date: (NSString *) follow_date;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
#endif
- (BOOL) user_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_desc;
- (void) setUser_desc: (NSString *) user_desc;
#endif
- (BOOL) user_descIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) user_gender;
- (void) setUser_gender: (int32_t) user_gender;
#endif
- (BOOL) user_genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_address;
- (void) setUser_address: (NSString *) user_address;
#endif
- (BOOL) user_addressIsSet;

#if !__has_feature(objc_arc)
- (int32_t) follow_state;
- (void) setFollow_state: (int32_t) follow_state;
#endif
- (BOOL) follow_stateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) follow_date;
- (void) setFollow_date: (NSString *) follow_date;
#endif
- (BOOL) follow_dateIsSet;

@end

@interface GetFollowListRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __host_domain;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __host_domain_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session host_domain: (NSString *) host_domain page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetFollowListResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __user_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __user_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=user_list, setter=setUser_list:) NSMutableArray * user_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count user_list: (NSMutableArray *) user_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) user_list;
- (void) setUser_list: (NSMutableArray *) user_list;
#endif
- (BOOL) user_listIsSet;

@end

@interface GetFollowerListRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __host_domain;
  int32_t __page_no;
  int32_t __page_size;

  BOOL __session_isset;
  BOOL __host_domain_isset;
  BOOL __page_no_isset;
  BOOL __page_size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=host_domain, setter=setHost_domain:) NSString * host_domain;
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session host_domain: (NSString *) host_domain page_no: (int32_t) page_no page_size: (int32_t) page_size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) host_domain;
- (void) setHost_domain: (NSString *) host_domain;
#endif
- (BOOL) host_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

@end

@interface GetFollowerListResponse : NSObject <TBase, NSCoding> {
  int32_t __page_no;
  int32_t __page_size;
  int32_t __count;
  NSMutableArray * __user_list;

  BOOL __page_no_isset;
  BOOL __page_size_isset;
  BOOL __count_isset;
  BOOL __user_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=page_no, setter=setPage_no:) int32_t page_no;
@property (nonatomic, getter=page_size, setter=setPage_size:) int32_t page_size;
@property (nonatomic, getter=count, setter=setCount:) int32_t count;
@property (nonatomic, retain, getter=user_list, setter=setUser_list:) NSMutableArray * user_list;
#endif

- (id) init;
- (id) initWithPage_no: (int32_t) page_no page_size: (int32_t) page_size count: (int32_t) count user_list: (NSMutableArray *) user_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) page_no;
- (void) setPage_no: (int32_t) page_no;
#endif
- (BOOL) page_noIsSet;

#if !__has_feature(objc_arc)
- (int32_t) page_size;
- (void) setPage_size: (int32_t) page_size;
#endif
- (BOOL) page_sizeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count;
- (void) setCount: (int32_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) user_list;
- (void) setUser_list: (NSMutableArray *) user_list;
#endif
- (BOOL) user_listIsSet;

@end

@interface AddPhotoLikeRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;

  BOOL __session_isset;
  BOOL __photo_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

@end

@interface DeletePhotoLikeRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;

  BOOL __session_isset;
  BOOL __photo_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

@end

@interface AddPocketLikeRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

@end

@interface DeletePocketLikeRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

@end

@interface AddPhotoRecommendRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;

  BOOL __session_isset;
  BOOL __photo_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

@end

@interface DeletePhotoRecommendRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __photo_id;

  BOOL __session_isset;
  BOOL __photo_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=photo_id, setter=setPhoto_id:) int64_t photo_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session photo_id: (int64_t) photo_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) photo_id;
- (void) setPhoto_id: (int64_t) photo_id;
#endif
- (BOOL) photo_idIsSet;

@end

@interface AddPocketRecommendRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

@end

@interface DeletePocketRecommendRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  int64_t __pocket_id;

  BOOL __session_isset;
  BOOL __pocket_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, getter=pocket_id, setter=setPocket_id:) int64_t pocket_id;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session pocket_id: (int64_t) pocket_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pocket_id;
- (void) setPocket_id: (int64_t) pocket_id;
#endif
- (BOOL) pocket_idIsSet;

@end

@interface GetUploadRequest : NSObject <TBase, NSCoding> {
  NSString * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface GetUploadResponse : NSObject <TBase, NSCoding> {
  NSString * __policy;
  NSString * __signature;
  NSString * __key_id;
  NSString * __object_key;

  BOOL __policy_isset;
  BOOL __signature_isset;
  BOOL __key_id_isset;
  BOOL __object_key_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=policy, setter=setPolicy:) NSString * policy;
@property (nonatomic, retain, getter=signature, setter=setSignature:) NSString * signature;
@property (nonatomic, retain, getter=key_id, setter=setKey_id:) NSString * key_id;
@property (nonatomic, retain, getter=object_key, setter=setObject_key:) NSString * object_key;
#endif

- (id) init;
- (id) initWithPolicy: (NSString *) policy signature: (NSString *) signature key_id: (NSString *) key_id object_key: (NSString *) object_key;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) policy;
- (void) setPolicy: (NSString *) policy;
#endif
- (BOOL) policyIsSet;

#if !__has_feature(objc_arc)
- (NSString *) signature;
- (void) setSignature: (NSString *) signature;
#endif
- (BOOL) signatureIsSet;

#if !__has_feature(objc_arc)
- (NSString *) key_id;
- (void) setKey_id: (NSString *) key_id;
#endif
- (BOOL) key_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) object_key;
- (void) setObject_key: (NSString *) object_key;
#endif
- (BOOL) object_keyIsSet;

@end

@interface PutStyleRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __banner_photo;

  BOOL __session_isset;
  BOOL __banner_photo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=banner_photo, setter=setBanner_photo:) NSString * banner_photo;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session banner_photo: (NSString *) banner_photo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) banner_photo;
- (void) setBanner_photo: (NSString *) banner_photo;
#endif
- (BOOL) banner_photoIsSet;

@end

@interface GetUserInfoRequest : NSObject <TBase, NSCoding> {
  NSString * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

@end

@interface GetUserInfoResponse : NSObject <TBase, NSCoding> {
  NSString * __user_name;
  NSString * __user_desc;
  NSString * __user_avatar;
  NSString * __user_domain;
  int32_t __gender;
  NSString * __birthday;
  NSString * __address;
  NSString * __qq;
  NSString * __weixin;
  NSString * __weibo;

  BOOL __user_name_isset;
  BOOL __user_desc_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
  BOOL __gender_isset;
  BOOL __birthday_isset;
  BOOL __address_isset;
  BOOL __qq_isset;
  BOOL __weixin_isset;
  BOOL __weibo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_desc, setter=setUser_desc:) NSString * user_desc;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
@property (nonatomic, getter=gender, setter=setGender:) int32_t gender;
@property (nonatomic, retain, getter=birthday, setter=setBirthday:) NSString * birthday;
@property (nonatomic, retain, getter=address, setter=setAddress:) NSString * address;
@property (nonatomic, retain, getter=qq, setter=setQq:) NSString * qq;
@property (nonatomic, retain, getter=weixin, setter=setWeixin:) NSString * weixin;
@property (nonatomic, retain, getter=weibo, setter=setWeibo:) NSString * weibo;
#endif

- (id) init;
- (id) initWithUser_name: (NSString *) user_name user_desc: (NSString *) user_desc user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain gender: (int32_t) gender birthday: (NSString *) birthday address: (NSString *) address qq: (NSString *) qq weixin: (NSString *) weixin weibo: (NSString *) weibo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_desc;
- (void) setUser_desc: (NSString *) user_desc;
#endif
- (BOOL) user_descIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gender;
- (void) setGender: (int32_t) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) birthday;
- (void) setBirthday: (NSString *) birthday;
#endif
- (BOOL) birthdayIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address;
- (void) setAddress: (NSString *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) qq;
- (void) setQq: (NSString *) qq;
#endif
- (BOOL) qqIsSet;

#if !__has_feature(objc_arc)
- (NSString *) weixin;
- (void) setWeixin: (NSString *) weixin;
#endif
- (BOOL) weixinIsSet;

#if !__has_feature(objc_arc)
- (NSString *) weibo;
- (void) setWeibo: (NSString *) weibo;
#endif
- (BOOL) weiboIsSet;

@end

@interface ModifyUserInfoRequest : NSObject <TBase, NSCoding> {
  NSString * __session;
  NSString * __user_name;
  NSString * __user_desc;
  NSString * __user_avatar;
  NSString * __user_domain;
  int32_t __gender;
  NSString * __birthday;
  NSString * __address;
  NSString * __qq;
  NSString * __weixin;
  NSString * __weibo;

  BOOL __session_isset;
  BOOL __user_name_isset;
  BOOL __user_desc_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
  BOOL __gender_isset;
  BOOL __birthday_isset;
  BOOL __address_isset;
  BOOL __qq_isset;
  BOOL __weixin_isset;
  BOOL __weibo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) NSString * session;
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_desc, setter=setUser_desc:) NSString * user_desc;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
@property (nonatomic, getter=gender, setter=setGender:) int32_t gender;
@property (nonatomic, retain, getter=birthday, setter=setBirthday:) NSString * birthday;
@property (nonatomic, retain, getter=address, setter=setAddress:) NSString * address;
@property (nonatomic, retain, getter=qq, setter=setQq:) NSString * qq;
@property (nonatomic, retain, getter=weixin, setter=setWeixin:) NSString * weixin;
@property (nonatomic, retain, getter=weibo, setter=setWeibo:) NSString * weibo;
#endif

- (id) init;
- (id) initWithSession: (NSString *) session user_name: (NSString *) user_name user_desc: (NSString *) user_desc user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain gender: (int32_t) gender birthday: (NSString *) birthday address: (NSString *) address qq: (NSString *) qq weixin: (NSString *) weixin weibo: (NSString *) weibo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) session;
- (void) setSession: (NSString *) session;
#endif
- (BOOL) sessionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_desc;
- (void) setUser_desc: (NSString *) user_desc;
#endif
- (BOOL) user_descIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gender;
- (void) setGender: (int32_t) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) birthday;
- (void) setBirthday: (NSString *) birthday;
#endif
- (BOOL) birthdayIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address;
- (void) setAddress: (NSString *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) qq;
- (void) setQq: (NSString *) qq;
#endif
- (BOOL) qqIsSet;

#if !__has_feature(objc_arc)
- (NSString *) weixin;
- (void) setWeixin: (NSString *) weixin;
#endif
- (BOOL) weixinIsSet;

#if !__has_feature(objc_arc)
- (NSString *) weibo;
- (void) setWeibo: (NSString *) weibo;
#endif
- (BOOL) weiboIsSet;

@end

@interface ModifyUserInfoResponse : NSObject <TBase, NSCoding> {
  NSString * __user_name;
  NSString * __user_desc;
  NSString * __user_avatar;
  NSString * __user_domain;
  int32_t __gender;
  NSString * __birthday;
  NSString * __address;
  NSString * __qq;
  NSString * __weixin;
  NSString * __weibo;

  BOOL __user_name_isset;
  BOOL __user_desc_isset;
  BOOL __user_avatar_isset;
  BOOL __user_domain_isset;
  BOOL __gender_isset;
  BOOL __birthday_isset;
  BOOL __address_isset;
  BOOL __qq_isset;
  BOOL __weixin_isset;
  BOOL __weibo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=user_name, setter=setUser_name:) NSString * user_name;
@property (nonatomic, retain, getter=user_desc, setter=setUser_desc:) NSString * user_desc;
@property (nonatomic, retain, getter=user_avatar, setter=setUser_avatar:) NSString * user_avatar;
@property (nonatomic, retain, getter=user_domain, setter=setUser_domain:) NSString * user_domain;
@property (nonatomic, getter=gender, setter=setGender:) int32_t gender;
@property (nonatomic, retain, getter=birthday, setter=setBirthday:) NSString * birthday;
@property (nonatomic, retain, getter=address, setter=setAddress:) NSString * address;
@property (nonatomic, retain, getter=qq, setter=setQq:) NSString * qq;
@property (nonatomic, retain, getter=weixin, setter=setWeixin:) NSString * weixin;
@property (nonatomic, retain, getter=weibo, setter=setWeibo:) NSString * weibo;
#endif

- (id) init;
- (id) initWithUser_name: (NSString *) user_name user_desc: (NSString *) user_desc user_avatar: (NSString *) user_avatar user_domain: (NSString *) user_domain gender: (int32_t) gender birthday: (NSString *) birthday address: (NSString *) address qq: (NSString *) qq weixin: (NSString *) weixin weibo: (NSString *) weibo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) user_name;
- (void) setUser_name: (NSString *) user_name;
#endif
- (BOOL) user_nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_desc;
- (void) setUser_desc: (NSString *) user_desc;
#endif
- (BOOL) user_descIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_avatar;
- (void) setUser_avatar: (NSString *) user_avatar;
#endif
- (BOOL) user_avatarIsSet;

#if !__has_feature(objc_arc)
- (NSString *) user_domain;
- (void) setUser_domain: (NSString *) user_domain;
#endif
- (BOOL) user_domainIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gender;
- (void) setGender: (int32_t) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) birthday;
- (void) setBirthday: (NSString *) birthday;
#endif
- (BOOL) birthdayIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address;
- (void) setAddress: (NSString *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) qq;
- (void) setQq: (NSString *) qq;
#endif
- (BOOL) qqIsSet;

#if !__has_feature(objc_arc)
- (NSString *) weixin;
- (void) setWeixin: (NSString *) weixin;
#endif
- (BOOL) weixinIsSet;

#if !__has_feature(objc_arc)
- (NSString *) weibo;
- (void) setWeibo: (NSString *) weibo;
#endif
- (BOOL) weiboIsSet;

@end

@interface userConstants : NSObject {
}
@end
